### ISSUE TITLE
Atualização de Quasar e VueJS 3

### ISSUE THREAD

**Issue by faelp22** [patrickmonteiro/quasar-apexcharts#34]
Gostei muito do seu exemplo, mas você teria um exemplo para a verão mais recente Quasar 2.3.1 e do VueJS 3?

**Comment by patrickmonteiro** [comment]
@faelp22  Olá, ainda não fiz um projeto exemplo para vue 3, porém aqui na documentação oficial há o tutorial de instalação para vue 2 e vue 3: https://apexcharts.com/docs/vue-charts/

**Comment by patrickmonteiro** [comment]
@faelp22 
Agora você pode ver a migração do projeto para quasar v2 com vue 3 através dessa branch: 
https://github.com/patrickmonteiro/quasar-apexcharts/tree/quasar-v2-vue3
