### ISSUE TITLE
Melhoria do gráfico do tipo RADAR

### ISSUE THREAD

**Issue by patrickmonteiro** [patrickmonteiro/quasar-apexcharts#5]
Atualmente o gráfico de radar já está implementado. Porém ele ainda não apresenta os pontos clicáveis para exibir o valor do ponto.

Exemplo da [documentação](https://apexcharts.com/vue-chart-demos/radar-charts/basic/) do apexcharts:

![Captura de Tela 2020-10-01 às 22 21 36](https://user-images.githubusercontent.com/13258255/94878698-83254380-0434-11eb-95a5-3e872e59d7e4.png)

- Gostaria que fosse implementado da mesma forma e que funcionasse tanto no mobile quanto desktop.
- Manter a responsividade e tamanho padrão já implementado.
- Na **PR** enviar print do projeto sendo executado localmente com o funcionamento do radar.

=)

**Comment by amimaro** [comment]
já comecei
