### ISSUE TITLE
Adicionar novo tipo de gráfico Treemap com cores distribuidas

### ISSUE THREAD

**Issue by patrickmonteiro** [patrickmonteiro/quasar-apexcharts#6]
Exemplo da [documentação](https://apexcharts.com/vue-chart-demos/treemap-charts/distributed/) do apexcharts:

![Captura de Tela 2020-10-01 às 22 27 17](https://user-images.githubusercontent.com/13258255/94878973-49087180-0435-11eb-8c89-6fd7559babcd.png)

- Gostaria que fosse implementado da mesma forma e que funcionasse tanto no mobile quanto desktop.
- Manter a responsividade e tamanho padrão já implementado.
- Na **PR** enviar print do projeto sendo executado localmente com o funcionamento do gráfico.
- A lista poderia ser de nomes de comunidades do norte, que tal ?

=)

**Comment by amimaro** [comment]
acabei fazendo hehe
agora tem que adicionar a label hacktoberfest

**Comment by amimaro** [comment]
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by patrickmonteiro** [comment]
Na verdade tem que add como tag no repo, farei em breve
