### ISSUE TITLE
Adicionar novo gráfico do tipo CandleStick

### ISSUE THREAD

**Issue by patrickmonteiro** [patrickmonteiro/quasar-apexcharts#8]
Exemplo da [documentação]https://apexcharts.com/vue-chart-demos/candlestick-charts/basic/ do apexcharts:

![Captura de Tela 2020-10-01 às 22 39 06](https://user-images.githubusercontent.com/13258255/94879559-ee701500-0436-11eb-8518-fe3dc9fadcb6.png)

- Gostaria que fosse implementado da mesma forma e que funcionasse tanto no mobile quanto desktop.
- Manter a responsividade e tamanho padrão já implementado.
- Na **PR** enviar print do projeto sendo executado localmente com o funcionamento do gráfico.
- Não é necessário implementar tantos pontos quanto no exemplo da documentação, uns 8 já estão de bom tamanho
=)

**Comment by amimaro** [comment]
acabei pegando essa issue. vou deixar as outras pro pessoal.

**Comment by patrickmonteiro** [comment]
@amimaro fique a vontade, tem muitas coisas a serem feitas ainda
